name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Docker Setup QEMU
      # You may pin to the exact commit or the version.
      # uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480
      uses: docker/setup-qemu-action@v1.2.0
    - name: Docker Setup Buildx
      # You may pin to the exact commit or the version.
      # uses: docker/setup-buildx-action@abe5d8f79a1606a2d3e218847032f3f2b1726ab0
      uses: docker/setup-buildx-action@v1.5.1
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      uses: docker/login-action@v1.10.0
      with:
        # Username used to log against the Docker registry
        username: ${{secrets.DOCKERHUB_USERNAME}}
        # Password or personal access token used to log against the Docker registry
        password: ${{secrets.DOCKERHUB_PASSWORD}}
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@1bc1040caef9e604eb543693ba89b5bf4fc80935
      uses: docker/build-push-action@v2.6.1
      with:
        context: .
        # Path to the Dockerfile
        file: ./Dockerfile
        # List of target platforms for build
        platforms: linux/amd64
        # Push is a shorthand for --output=type=registry
        push: true
        tags: brisco007/python-helloworld:latest
