name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Python Dependency Installation
      # You may pin to the exact commit or the version.
      # uses: py-actions/py-dependency-install@3c3cdbee1f1761659b685ec4b146e0f4ac59e9b4
      uses: py-actions/py-dependency-install@v2.1.0
      with:
        path: ./requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
